# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  updateweb:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Run
      run: | 
        cd $GITHUB_WORKSPACE/.github/webui
        dotnet run $GITHUB_WORKSPACE
        mkdir $GITHUB_WORKSPACE/deploy
        mv $GITHUB_WORKSPACE/.github/webui/*.html $GITHUB_WORKSPACE/deploy/
        mv $GITHUB_WORKSPACE/.github/webui/*.js $GITHUB_WORKSPACE/deploy/
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
          path: 'deploy'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
